spring:
  application:
    name: hinitializer
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23li6uv8oZuXSMxGO5
            client-secret: 0a77eca8f648d036efcafbac2216a0abc4f61e2b
            scope: read:user
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:./data/mydata
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update