name: Build and Deploy to Cloud Run

on:
  release:
    types: 
      - created

env:
  GCP_REGION: europe-west3
  SERVICE_NAME: hinvento-spring
  #SERVICE_URL is added at first run; See step "Retrieve Cloud Run DNS Name"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 21
        distribution: temurin

    - name: Log in to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Configure Docker for GCP
      run: gcloud auth configure-docker $GCP_REGION-docker.pkg.dev --quiet

    - name: Build and Push Docker Image
      run: |
        RELEASE_TAG=${{ github.event.release.tag_name }}
        IMAGE_NAME=$GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/docker-repo/$SERVICE_NAME
        docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$RELEASE_TAG .
        docker push $IMAGE_NAME:latest
        docker push $IMAGE_NAME:$RELEASE_TAG
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        GCP_REGION: ${{ env.GCP_REGION }}
        SERVICE_NAME: ${{ env.SERVICE_NAME }}

    - name: Deploy to Cloud Run
      run: |
        RELEASE_TAG=${{ github.event.release.tag_name }}
        gcloud run deploy $SERVICE_NAME \
          --image $GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/docker-repo/$SERVICE_NAME:$RELEASE_TAG \
          --platform managed \
          --region $GCP_REGION \
          --allow-unauthenticated
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        GCP_REGION: ${{ env.GCP_REGION }}
        SERVICE_NAME: ${{ env.SERVICE_NAME }}

    - name: Retrieve Cloud Run DNS Name
      id: get-dns
      run: |
        SERVICE_URL=$(gcloud run services describe $SERVICE_NAME \
          --region $GCP_REGION \
          --format='value(status.url)')
        echo "Cloud Run service URL: $SERVICE_URL"
        echo "SERVICE_URL=$SERVICE_URL" >> $GITHUB_ENV
      env:
        GCP_REGION: ${{ env.GCP_REGION }}
        SERVICE_NAME: ${{ env.SERVICE_NAME }}

    - name: Log the Service DNS Name
      run: echo "Deployed service URL: ${{ env.SERVICE_URL }}"
      env:
        SERVICE_URL: ${{ env.SERVICE_URL }}
